config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :client_registrations
      resources :customisations
      resources :enquiries
      resources :enquiry_details_pages
      resources :homes
      resources :operations_teams
      resources :orders
      resources :supplier_registrations

      root to: "users#index"
    end
      devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
 
  resources :supplier_registrations
  resources :orders
  resources :operations_teams
  resources :homes
  resources :enquiry_details_pages
  resources :enquiries
  resources :customisations
  resources :client_registrations
  root to:"homes#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
# == Route Map
#
#                           Prefix Verb   URI Pattern                                                                              Controller#Action
#                      admin_users GET    /admin/users(.:format)                                                                   admin/users#index
#                                  POST   /admin/users(.:format)                                                                   admin/users#create
#                   new_admin_user GET    /admin/users/new(.:format)                                                               admin/users#new
#                  edit_admin_user GET    /admin/users/:id/edit(.:format)                                                          admin/users#edit
#                       admin_user GET    /admin/users/:id(.:format)                                                               admin/users#show
#                                  PATCH  /admin/users/:id(.:format)                                                               admin/users#update
#                                  PUT    /admin/users/:id(.:format)                                                               admin/users#update
#                                  DELETE /admin/users/:id(.:format)                                                               admin/users#destroy
#       admin_client_registrations GET    /admin/client_registrations(.:format)                                                    admin/client_registrations#index
#                                  POST   /admin/client_registrations(.:format)                                                    admin/client_registrations#create
#    new_admin_client_registration GET    /admin/client_registrations/new(.:format)                                                admin/client_registrations#new
#   edit_admin_client_registration GET    /admin/client_registrations/:id/edit(.:format)                                           admin/client_registrations#edit
#        admin_client_registration GET    /admin/client_registrations/:id(.:format)                                                admin/client_registrations#show
#                                  PATCH  /admin/client_registrations/:id(.:format)                                                admin/client_registrations#update
#                                  PUT    /admin/client_registrations/:id(.:format)                                                admin/client_registrations#update
#                                  DELETE /admin/client_registrations/:id(.:format)                                                admin/client_registrations#destroy
#             admin_customisations GET    /admin/customisations(.:format)                                                          admin/customisations#index
#                                  POST   /admin/customisations(.:format)                                                          admin/customisations#create
#          new_admin_customisation GET    /admin/customisations/new(.:format)                                                      admin/customisations#new
#         edit_admin_customisation GET    /admin/customisations/:id/edit(.:format)                                                 admin/customisations#edit
#              admin_customisation GET    /admin/customisations/:id(.:format)                                                      admin/customisations#show
#                                  PATCH  /admin/customisations/:id(.:format)                                                      admin/customisations#update
#                                  PUT    /admin/customisations/:id(.:format)                                                      admin/customisations#update
#                                  DELETE /admin/customisations/:id(.:format)                                                      admin/customisations#destroy
#                  admin_enquiries GET    /admin/enquiries(.:format)                                                               admin/enquiries#index
#                                  POST   /admin/enquiries(.:format)                                                               admin/enquiries#create
#                new_admin_enquiry GET    /admin/enquiries/new(.:format)                                                           admin/enquiries#new
#               edit_admin_enquiry GET    /admin/enquiries/:id/edit(.:format)                                                      admin/enquiries#edit
#                    admin_enquiry GET    /admin/enquiries/:id(.:format)                                                           admin/enquiries#show
#                                  PATCH  /admin/enquiries/:id(.:format)                                                           admin/enquiries#update
#                                  PUT    /admin/enquiries/:id(.:format)                                                           admin/enquiries#update
#                                  DELETE /admin/enquiries/:id(.:format)                                                           admin/enquiries#destroy
#      admin_enquiry_details_pages GET    /admin/enquiry_details_pages(.:format)                                                   admin/enquiry_details_pages#index
#                                  POST   /admin/enquiry_details_pages(.:format)                                                   admin/enquiry_details_pages#create
#   new_admin_enquiry_details_page GET    /admin/enquiry_details_pages/new(.:format)                                               admin/enquiry_details_pages#new
#  edit_admin_enquiry_details_page GET    /admin/enquiry_details_pages/:id/edit(.:format)                                          admin/enquiry_details_pages#edit
#       admin_enquiry_details_page GET    /admin/enquiry_details_pages/:id(.:format)                                               admin/enquiry_details_pages#show
#                                  PATCH  /admin/enquiry_details_pages/:id(.:format)                                               admin/enquiry_details_pages#update
#                                  PUT    /admin/enquiry_details_pages/:id(.:format)                                               admin/enquiry_details_pages#update
#                                  DELETE /admin/enquiry_details_pages/:id(.:format)                                               admin/enquiry_details_pages#destroy
#                      admin_homes GET    /admin/homes(.:format)                                                                   admin/homes#index
#                                  POST   /admin/homes(.:format)                                                                   admin/homes#create
#                   new_admin_home GET    /admin/homes/new(.:format)                                                               admin/homes#new
#                  edit_admin_home GET    /admin/homes/:id/edit(.:format)                                                          admin/homes#edit
#                       admin_home GET    /admin/homes/:id(.:format)                                                               admin/homes#show
#                                  PATCH  /admin/homes/:id(.:format)                                                               admin/homes#update
#                                  PUT    /admin/homes/:id(.:format)                                                               admin/homes#update
#                                  DELETE /admin/homes/:id(.:format)                                                               admin/homes#destroy
#           admin_operations_teams GET    /admin/operations_teams(.:format)                                                        admin/operations_teams#index
#                                  POST   /admin/operations_teams(.:format)                                                        admin/operations_teams#create
#        new_admin_operations_team GET    /admin/operations_teams/new(.:format)                                                    admin/operations_teams#new
#       edit_admin_operations_team GET    /admin/operations_teams/:id/edit(.:format)                                               admin/operations_teams#edit
#            admin_operations_team GET    /admin/operations_teams/:id(.:format)                                                    admin/operations_teams#show
#                                  PATCH  /admin/operations_teams/:id(.:format)                                                    admin/operations_teams#update
#                                  PUT    /admin/operations_teams/:id(.:format)                                                    admin/operations_teams#update
#                                  DELETE /admin/operations_teams/:id(.:format)                                                    admin/operations_teams#destroy
#                     admin_orders GET    /admin/orders(.:format)                                                                  admin/orders#index

app/models/client_registration.rb
# == Schema Information
#
# Table name: client_registrations
#
#  id                      :bigint           not null, primary key
#  company_name            :string(255)
#  buyer_name              :string(255)
#  phone_number            :string(255)
#  email_id                :string(255)
#  mobile_number           :integer
#  purchasing_manager_name :string(255)
#  address                 :string(255)
#  nature_of_business      :string(255)
#  login_id                :string(255)
#  tenant_id               :string(255)
#  client_registration_id  :string(255)
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class ClientRegistration < ApplicationRecord
end

app/controllers/admin/client_registrations_controller.rb
module Admin
  class ClientRegistrationsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = ClientRegistration.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   ClientRegistration.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/client_registrations_controller.rb
class ClientRegistrationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client_registration, only: [:show, :update, :destroy]

  # GET /client_registrations
  # GET /client_registrations.json
  def index
    @client_registrations = ClientRegistration.all
  end

  # GET /client_registrations/1
  # GET /client_registrations/1.json
  def show
  end
   # GET /client_registrations/new
  def new
    @client_registration = ClientRegistration.new
   
  end
  # POST /client_registrations
  # POST /client_registrations.json
  def create
    @client_registration = ClientRegistration.new(client_registration_params)

    if @client_registration.save
      render :show, status: :created, location: @client_registration
    else
      render json: @client_registration.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /client_registrations/1
  # PATCH/PUT /client_registrations/1.json
  def update
    if @client_registration.update(client_registration_params)
      render :show, status: :ok, location: @client_registration
    else
      render json: @client_registration.errors, status: :unprocessable_entity
    end
  end

  # DELETE /client_registrations/1
  # DELETE /client_registrations/1.json
  def destroy
    @client_registration.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_registration
      @client_registration = ClientRegistration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_registration_params
      params.require(:client_registration).permit(:company_name, :buyer_name, :phone_number, :email_id, :mobile_number, :purchasing_manager_name, :address, :nature_of_business, :login_id, :tenant_id, :client_registration_id)
    end
end

app/views/client_registrations/_form.html.erb
<%= form_with(model: client_registration, local: true) do |form| %>
  <% if client_registration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client_registration.errors.count, "error") %> prohibited this client_registration from being saved:</h2>

      <ul>
      <% client_registration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :buyer_name %>
    <%= form.text_field :buyer_name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :email_id %>
    <%= form.text_field :email_id %>
  </div>

  <div class="field">
    <%= form.label :mobile_number %>
    <%= form.number_field :mobile_number %>
  </div>

  <div class="field">
    <%= form.label :purchasing_manager_name %>
    <%= form.text_field :purchasing_manager_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :nature_of_business %>
    <%= form.text_field :nature_of_business %>
  </div>

  <div class="field">
    <%= form.label :login_id %>
    <%= form.text_field :login_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/client_registrations/edit.html.erb
<h1>Editing Client Registration</h1>

<%= render 'form', client_registration: @client_registration %>

<%= link_to 'Show', @client_registration %> |
<%= link_to 'Back', client_registrations_path %>

app/views/client_registrations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Client Registrations</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Buyer name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Mobile number</th>
      <th>Purchasing manager name</th>
      <th>Address</th>
      <th>Nature of business</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @client_registrations.each do |client_registration| %>
      <tr>
        <td><%= client_registration.company_name %></td>
        <td><%= client_registration.buyer_name %></td>
        <td><%= client_registration.phone_number %></td>
        <td><%= client_registration.email_id %></td>
        <td><%= client_registration.mobile_number %></td>
        <td><%= client_registration.purchasing_manager_name %></td>
        <td><%= client_registration.address %></td>
        <td><%= client_registration.nature_of_business %></td>
        <td><%= client_registration.login_id %></td>
        <td><%= link_to 'Show', client_registration %></td>
        <td><%= link_to 'Edit', edit_client_registration_path(client_registration) %></td>
        <td><%= link_to 'Destroy', client_registration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client Registration', new_client_registration_path %>

app/views/client_registrations/new.html.erb
<h1>New Client Registration</h1>

<%= render 'form', client_registration: @client_registration %>

<%= link_to 'Back', client_registrations_path %>

app/views/client_registrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @client_registration.company_name %>
</p>

<p>
  <strong>Buyer name:</strong>
  <%= @client_registration.buyer_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @client_registration.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client_registration.email_id %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @client_registration.mobile_number %>
</p>

<p>
  <strong>Purchasing manager name:</strong>
  <%= @client_registration.purchasing_manager_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client_registration.address %>
</p>

<p>
  <strong>Nature of business:</strong>
  <%= @client_registration.nature_of_business %>
</p>

<p>
  <strong>Login:</strong>
  <%= @client_registration.login_id %>
</p>

<%= link_to 'Edit', edit_client_registration_path(@client_registration) %> |
<%= link_to 'Back', client_registrations_path %>