config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :client_registrations
      resources :customisations
      resources :enquiries
      resources :enquiry_details_pages
      resources :homes
      resources :operations_teams
      resources :orders
      resources :supplier_registrations

      root to: "users#index"
    end
      devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
 
  resources :supplier_registrations
  resources :orders
  resources :operations_teams
  resources :homes
  resources :enquiry_details_pages
  resources :enquiries
  resources :customisations
  resources :client_registrations
  root to:"homes#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
# == Route Map
#
#                           Prefix Verb   URI Pattern                                                                              Controller#Action
#                      admin_users GET    /admin/users(.:format)                                                                   admin/users#index
#                                  POST   /admin/users(.:format)                                                                   admin/users#create
#                   new_admin_user GET    /admin/users/new(.:format)                                                               admin/users#new
#                  edit_admin_user GET    /admin/users/:id/edit(.:format)                                                          admin/users#edit
#                       admin_user GET    /admin/users/:id(.:format)                                                               admin/users#show
#                                  PATCH  /admin/users/:id(.:format)                                                               admin/users#update
#                                  PUT    /admin/users/:id(.:format)                                                               admin/users#update
#                                  DELETE /admin/users/:id(.:format)                                                               admin/users#destroy
#       admin_client_registrations GET    /admin/client_registrations(.:format)                                                    admin/client_registrations#index
#                                  POST   /admin/client_registrations(.:format)                                                    admin/client_registrations#create
#    new_admin_client_registration GET    /admin/client_registrations/new(.:format)                                                admin/client_registrations#new
#   edit_admin_client_registration GET    /admin/client_registrations/:id/edit(.:format)                                           admin/client_registrations#edit
#        admin_client_registration GET    /admin/client_registrations/:id(.:format)                                                admin/client_registrations#show
#                                  PATCH  /admin/client_registrations/:id(.:format)                                                admin/client_registrations#update
#                                  PUT    /admin/client_registrations/:id(.:format)                                                admin/client_registrations#update
#                                  DELETE /admin/client_registrations/:id(.:format)                                                admin/client_registrations#destroy
#             admin_customisations GET    /admin/customisations(.:format)                                                          admin/customisations#index
#                                  POST   /admin/customisations(.:format)                                                          admin/customisations#create
#          new_admin_customisation GET    /admin/customisations/new(.:format)                                                      admin/customisations#new
#         edit_admin_customisation GET    /admin/customisations/:id/edit(.:format)                                                 admin/customisations#edit
#              admin_customisation GET    /admin/customisations/:id(.:format)                                                      admin/customisations#show
#                                  PATCH  /admin/customisations/:id(.:format)                                                      admin/customisations#update
#                                  PUT    /admin/customisations/:id(.:format)                                                      admin/customisations#update
#                                  DELETE /admin/customisations/:id(.:format)                                                      admin/customisations#destroy
#                  admin_enquiries GET    /admin/enquiries(.:format)                                                               admin/enquiries#index
#                                  POST   /admin/enquiries(.:format)                                                               admin/enquiries#create
#                new_admin_enquiry GET    /admin/enquiries/new(.:format)                                                           admin/enquiries#new
#               edit_admin_enquiry GET    /admin/enquiries/:id/edit(.:format)                                                      admin/enquiries#edit
#                    admin_enquiry GET    /admin/enquiries/:id(.:format)                                                           admin/enquiries#show
#                                  PATCH  /admin/enquiries/:id(.:format)                                                           admin/enquiries#update
#                                  PUT    /admin/enquiries/:id(.:format)                                                           admin/enquiries#update
#                                  DELETE /admin/enquiries/:id(.:format)                                                           admin/enquiries#destroy
#      admin_enquiry_details_pages GET    /admin/enquiry_details_pages(.:format)                                                   admin/enquiry_details_pages#index
#                                  POST   /admin/enquiry_details_pages(.:format)                                                   admin/enquiry_details_pages#create
#   new_admin_enquiry_details_page GET    /admin/enquiry_details_pages/new(.:format)                                               admin/enquiry_details_pages#new
#  edit_admin_enquiry_details_page GET    /admin/enquiry_details_pages/:id/edit(.:format)                                          admin/enquiry_details_pages#edit
#       admin_enquiry_details_page GET    /admin/enquiry_details_pages/:id(.:format)                                               admin/enquiry_details_pages#show
#                                  PATCH  /admin/enquiry_details_pages/:id(.:format)                                               admin/enquiry_details_pages#update
#                                  PUT    /admin/enquiry_details_pages/:id(.:format)                                               admin/enquiry_details_pages#update
#                                  DELETE /admin/enquiry_details_pages/:id(.:format)                                               admin/enquiry_details_pages#destroy
#                      admin_homes GET    /admin/homes(.:format)                                                                   admin/homes#index
#                                  POST   /admin/homes(.:format)                                                                   admin/homes#create
#                   new_admin_home GET    /admin/homes/new(.:format)                                                               admin/homes#new
#                  edit_admin_home GET    /admin/homes/:id/edit(.:format)                                                          admin/homes#edit
#                       admin_home GET    /admin/homes/:id(.:format)                                                               admin/homes#show
#                                  PATCH  /admin/homes/:id(.:format)                                                               admin/homes#update
#                                  PUT    /admin/homes/:id(.:format)                                                               admin/homes#update
#                                  DELETE /admin/homes/:id(.:format)                                                               admin/homes#destroy
#           admin_operations_teams GET    /admin/operations_teams(.:format)                                                        admin/operations_teams#index
#                                  POST   /admin/operations_teams(.:format)                                                        admin/operations_teams#create
#        new_admin_operations_team GET    /admin/operations_teams/new(.:format)                                                    admin/operations_teams#new
#       edit_admin_operations_team GET    /admin/operations_teams/:id/edit(.:format)                                               admin/operations_teams#edit
#            admin_operations_team GET    /admin/operations_teams/:id(.:format)                                                    admin/operations_teams#show
#                                  PATCH  /admin/operations_teams/:id(.:format)                                                    admin/operations_teams#update
#                                  PUT    /admin/operations_teams/:id(.:format)                                                    admin/operations_teams#update
#                                  DELETE /admin/operations_teams/:id(.:format)                                                    admin/operations_teams#destroy
#                     admin_orders GET    /admin/orders(.:format)                                                                  admin/orders#index

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id                              :bigint           not null, primary key
#  customer_name                   :string(255)
#  enquiry_number                  :string(255)
#  client_name                     :string(255)
#  enquiry_for                     :string(255)
#  color                           :string(255)
#  material                        :string(255)
#  gsm                             :string(255)
#  quantity                        :integer
#  sizes                           :string(255)
#  printing                        :string(255)
#  embroidery                      :string(255)
#  place_of_printing               :string(255)
#  payment_terms                   :string(255)
#  client_target_price             :string(255)
#  client_target_delivery_schedule :string(255)
#  offered_price                   :string(255)
#  offered_delivery_schedule       :string(255)
#  status_of_the_enquiry           :string(255)
#  supplier_name                   :string(255)
#  sample_readiness                :string(255)
#  sample__delivery                :string(255)
#  advance_received                :string(255)
#  status_of_the_order             :string(255)
#  owner_of_the_otask              :string(255)
#  tenant_id                       :string(255)
#  created_at                      :datetime         not null
#  updated_at                      :datetime         not null
#

class Order < ApplicationRecord
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Order.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Order.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end
  # GET /orders/new
  def new
    @order = Order.new

  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    if @order.save
      render :show, status: :created, location: @order
    else
      render json: @order.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    if @order.update(order_params)
      render :show, status: :ok, location: @order
    else
      render json: @order.errors, status: :unprocessable_entity
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_name, :enquiry_number, :client_name, :enquiry_for, :color, :material, :gsm, :quantity, :sizes, :printing, :embroidery, :place_of_printing, :payment_terms, :client_target_price, :client_target_delivery_schedule, :offered_price, :offered_delivery_schedule, :status_of_the_enquiry, :supplier_name, :sample_readiness, :sample__delivery, :advance_received, :status_of_the_order, :owner_of_the_otask, :tenant_id)
    end
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name %>
  </div>

  <div class="field">
    <%= form.label :enquiry_number %>
    <%= form.text_field :enquiry_number %>
  </div>

  <div class="field">
    <%= form.label :client_name %>
    <%= form.text_field :client_name %>
  </div>

  <div class="field">
    <%= form.label :enquiry_for %>
    <%= form.text_field :enquiry_for %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :material %>
    <%= form.text_field :material %>
  </div>

  <div class="field">
    <%= form.label :gsm %>
    <%= form.text_field :gsm %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :sizes %>
    <%= form.text_field :sizes %>
  </div>

  <div class="field">
    <%= form.label :printing %>
    <%= form.text_field :printing %>
  </div>

  <div class="field">
    <%= form.label :embroidery %>
    <%= form.text_field :embroidery %>
  </div>

  <div class="field">
    <%= form.label :place_of_printing %>
    <%= form.text_field :place_of_printing %>
  </div>

  <div class="field">
    <%= form.label :payment_terms %>
    <%= form.text_field :payment_terms %>
  </div>

  <div class="field">
    <%= form.label :client_target_price %>
    <%= form.text_field :client_target_price %>
  </div>

  <div class="field">
    <%= form.label :client_target_delivery_schedule %>
    <%= form.text_field :client_target_delivery_schedule %>
  </div>

  <div class="field">
    <%= form.label :offered_price %>
    <%= form.text_field :offered_price %>
  </div>

  <div class="field">
    <%= form.label :offered_delivery_schedule %>
    <%= form.text_field :offered_delivery_schedule %>
  </div>

  <div class="field">
    <%= form.label :owner_of_the_etask %>
    <%= form.text_field :owner_of_the_etask %>
  </div>

  <div class="field">
    <%= form.label :status_of_the_enquiry %>
    <%= form.text_field :status_of_the_enquiry %>
  </div>

  <div class="field">
    <%= form.label :supplier_name %>
    <%= form.text_field :supplier_name %>
  </div>

  <div class="field">
    <%= form.label :sample_readiness %>
    <%= form.text_field :sample_readiness %>
  </div>

  <div class="field">
    <%= form.label :sample_delivery %>
    <%= form.text_field :sample_delivery %>
  </div>

  <div class="field">
    <%= form.label :advance_received %>
    <%= form.text_field :advance_received %>
  </div>

  <div class="field">
    <%= form.label :status_of_the_order %>
    <%= form.text_field :status_of_the_order %>
  </div>

  <div class="field">
    <%= form.label :owner_of_the_otask %>
    <%= form.text_field :owner_of_the_otask %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Customer name</th>
      <th>Enquiry number</th>
      <th>Client name</th>
      <th>Enquiry for</th>
      <th>Color</th>
      <th>Material</th>
      <th>Gsm</th>
      <th>Quantity</th>
      <th>Sizes</th>
      <th>Printing</th>
      <th>Embroidery</th>
      <th>Place of printing</th>
      <th>Payment terms</th>
      <th>Client target price</th>
      <th>Client target delivery schedule</th>
      <th>Offered price</th>
      <th>Offered delivery schedule</th>
      <th>Owner of the etask</th>
      <th>Status of the enquiry</th>
      <th>Supplier name</th>
      <th>Sample readiness</th>
      <th>Sample delivery</th>
      <th>Advance received</th>
      <th>Status of the order</th>
      <th>Owner of the otask</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.customer_name %></td>
        <td><%= order.enquiry_number %></td>
        <td><%= order.client_name %></td>
        <td><%= order.enquiry_for %></td>
        <td><%= order.color %></td>
        <td><%= order.material %></td>
        <td><%= order.gsm %></td>
        <td><%= order.quantity %></td>
        <td><%= order.sizes %></td>
        <td><%= order.printing %></td>
        <td><%= order.embroidery %></td>
        <td><%= order.place_of_printing %></td>
        <td><%= order.payment_terms %></td>
        <td><%= order.client_target_price %></td>
        <td><%= order.client_target_delivery_schedule %></td>
        <td><%= order.offered_price %></td>
        <td><%= order.offered_delivery_schedule %></td>
        <td><%= order.owner_of_the_etask %></td>
        <td><%= order.status_of_the_enquiry %></td>
        <td><%= order.supplier_name %></td>
        <td><%= order.sample_readiness %></td>
        <td><%= order.sample_delivery %></td>
        <td><%= order.advance_received %></td>
        <td><%= order.status_of_the_order %></td>
        <td><%= order.owner_of_the_otask %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer name:</strong>
  <%= @order.customer_name %>
</p>

<p>
  <strong>Enquiry number:</strong>
  <%= @order.enquiry_number %>
</p>

<p>
  <strong>Client name:</strong>
  <%= @order.client_name %>
</p>

<p>
  <strong>Enquiry for:</strong>
  <%= @order.enquiry_for %>
</p>

<p>
  <strong>Color:</strong>
  <%= @order.color %>
</p>

<p>
  <strong>Material:</strong>
  <%= @order.material %>
</p>

<p>
  <strong>Gsm:</strong>
  <%= @order.gsm %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<p>
  <strong>Sizes:</strong>
  <%= @order.sizes %>
</p>

<p>
  <strong>Printing:</strong>
  <%= @order.printing %>
</p>

<p>
  <strong>Embroidery:</strong>
  <%= @order.embroidery %>
</p>

<p>
  <strong>Place of printing:</strong>
  <%= @order.place_of_printing %>
</p>

<p>
  <strong>Payment terms:</strong>
  <%= @order.payment_terms %>
</p>

<p>
  <strong>Client target price:</strong>
  <%= @order.client_target_price %>
</p>

<p>
  <strong>Client target delivery schedule:</strong>
  <%= @order.client_target_delivery_schedule %>
</p>

<p>
  <strong>Offered price:</strong>
  <%= @order.offered_price %>
</p>

<p>
  <strong>Offered delivery schedule:</strong>
  <%= @order.offered_delivery_schedule %>
</p>

<p>
  <strong>Owner of the etask:</strong>
  <%= @order.owner_of_the_etask %>
</p>

<p>
  <strong>Status of the enquiry:</strong>
  <%= @order.status_of_the_enquiry %>
</p>

<p>
  <strong>Supplier name:</strong>
  <%= @order.supplier_name %>
</p>

<p>
  <strong>Sample readiness:</strong>
  <%= @order.sample_readiness %>
</p>

<p>
  <strong>Sample delivery:</strong>
  <%= @order.sample_delivery %>
</p>

<p>
  <strong>Advance received:</strong>
  <%= @order.advance_received %>
</p>

<p>
  <strong>Status of the order:</strong>
  <%= @order.status_of_the_order %>
</p>

<p>
  <strong>Owner of the otask:</strong>
  <%= @order.owner_of_the_otask %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>