config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :client_registrations
      resources :customisations
      resources :enquiries
      resources :enquiry_details_pages
      resources :homes
      resources :operations_teams
      resources :orders
      resources :supplier_registrations

      root to: "users#index"
    end
      devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
 
  resources :supplier_registrations
  resources :orders
  resources :operations_teams
  resources :homes
  resources :enquiry_details_pages
  resources :enquiries
  resources :customisations
  resources :client_registrations
  root to:"homes#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
# == Route Map
#
#                           Prefix Verb   URI Pattern                                                                              Controller#Action
#                      admin_users GET    /admin/users(.:format)                                                                   admin/users#index
#                                  POST   /admin/users(.:format)                                                                   admin/users#create
#                   new_admin_user GET    /admin/users/new(.:format)                                                               admin/users#new
#                  edit_admin_user GET    /admin/users/:id/edit(.:format)                                                          admin/users#edit
#                       admin_user GET    /admin/users/:id(.:format)                                                               admin/users#show
#                                  PATCH  /admin/users/:id(.:format)                                                               admin/users#update
#                                  PUT    /admin/users/:id(.:format)                                                               admin/users#update
#                                  DELETE /admin/users/:id(.:format)                                                               admin/users#destroy
#       admin_client_registrations GET    /admin/client_registrations(.:format)                                                    admin/client_registrations#index
#                                  POST   /admin/client_registrations(.:format)                                                    admin/client_registrations#create
#    new_admin_client_registration GET    /admin/client_registrations/new(.:format)                                                admin/client_registrations#new
#   edit_admin_client_registration GET    /admin/client_registrations/:id/edit(.:format)                                           admin/client_registrations#edit
#        admin_client_registration GET    /admin/client_registrations/:id(.:format)                                                admin/client_registrations#show
#                                  PATCH  /admin/client_registrations/:id(.:format)                                                admin/client_registrations#update
#                                  PUT    /admin/client_registrations/:id(.:format)                                                admin/client_registrations#update
#                                  DELETE /admin/client_registrations/:id(.:format)                                                admin/client_registrations#destroy
#             admin_customisations GET    /admin/customisations(.:format)                                                          admin/customisations#index
#                                  POST   /admin/customisations(.:format)                                                          admin/customisations#create
#          new_admin_customisation GET    /admin/customisations/new(.:format)                                                      admin/customisations#new
#         edit_admin_customisation GET    /admin/customisations/:id/edit(.:format)                                                 admin/customisations#edit
#              admin_customisation GET    /admin/customisations/:id(.:format)                                                      admin/customisations#show
#                                  PATCH  /admin/customisations/:id(.:format)                                                      admin/customisations#update
#                                  PUT    /admin/customisations/:id(.:format)                                                      admin/customisations#update
#                                  DELETE /admin/customisations/:id(.:format)                                                      admin/customisations#destroy
#                  admin_enquiries GET    /admin/enquiries(.:format)                                                               admin/enquiries#index
#                                  POST   /admin/enquiries(.:format)                                                               admin/enquiries#create
#                new_admin_enquiry GET    /admin/enquiries/new(.:format)                                                           admin/enquiries#new
#               edit_admin_enquiry GET    /admin/enquiries/:id/edit(.:format)                                                      admin/enquiries#edit
#                    admin_enquiry GET    /admin/enquiries/:id(.:format)                                                           admin/enquiries#show
#                                  PATCH  /admin/enquiries/:id(.:format)                                                           admin/enquiries#update
#                                  PUT    /admin/enquiries/:id(.:format)                                                           admin/enquiries#update
#                                  DELETE /admin/enquiries/:id(.:format)                                                           admin/enquiries#destroy
#      admin_enquiry_details_pages GET    /admin/enquiry_details_pages(.:format)                                                   admin/enquiry_details_pages#index
#                                  POST   /admin/enquiry_details_pages(.:format)                                                   admin/enquiry_details_pages#create
#   new_admin_enquiry_details_page GET    /admin/enquiry_details_pages/new(.:format)                                               admin/enquiry_details_pages#new
#  edit_admin_enquiry_details_page GET    /admin/enquiry_details_pages/:id/edit(.:format)                                          admin/enquiry_details_pages#edit
#       admin_enquiry_details_page GET    /admin/enquiry_details_pages/:id(.:format)                                               admin/enquiry_details_pages#show
#                                  PATCH  /admin/enquiry_details_pages/:id(.:format)                                               admin/enquiry_details_pages#update
#                                  PUT    /admin/enquiry_details_pages/:id(.:format)                                               admin/enquiry_details_pages#update
#                                  DELETE /admin/enquiry_details_pages/:id(.:format)                                               admin/enquiry_details_pages#destroy
#                      admin_homes GET    /admin/homes(.:format)                                                                   admin/homes#index
#                                  POST   /admin/homes(.:format)                                                                   admin/homes#create
#                   new_admin_home GET    /admin/homes/new(.:format)                                                               admin/homes#new
#                  edit_admin_home GET    /admin/homes/:id/edit(.:format)                                                          admin/homes#edit
#                       admin_home GET    /admin/homes/:id(.:format)                                                               admin/homes#show
#                                  PATCH  /admin/homes/:id(.:format)                                                               admin/homes#update
#                                  PUT    /admin/homes/:id(.:format)                                                               admin/homes#update
#                                  DELETE /admin/homes/:id(.:format)                                                               admin/homes#destroy
#           admin_operations_teams GET    /admin/operations_teams(.:format)                                                        admin/operations_teams#index
#                                  POST   /admin/operations_teams(.:format)                                                        admin/operations_teams#create
#        new_admin_operations_team GET    /admin/operations_teams/new(.:format)                                                    admin/operations_teams#new
#       edit_admin_operations_team GET    /admin/operations_teams/:id/edit(.:format)                                               admin/operations_teams#edit
#            admin_operations_team GET    /admin/operations_teams/:id(.:format)                                                    admin/operations_teams#show
#                                  PATCH  /admin/operations_teams/:id(.:format)                                                    admin/operations_teams#update
#                                  PUT    /admin/operations_teams/:id(.:format)                                                    admin/operations_teams#update
#                                  DELETE /admin/operations_teams/:id(.:format)                                                    admin/operations_teams#destroy
#                     admin_orders GET    /admin/orders(.:format)                                                                  admin/orders#index

app/models/enquiry.rb
# == Schema Information
#
# Table name: enquiries
#
#  id                              :bigint           not null, primary key
#  client_name                     :string(255)
#  enquiry_for                     :string(255)
#  color                           :string(255)
#  material                        :string(255)
#  gsm                             :string(255)
#  quantity                        :integer
#  sizes                           :string(255)
#  printing                        :string(255)
#  embroidery                      :string(255)
#  place_of_printing               :string(255)
#  payment_terms                   :string(255)
#  client_target_price             :string(255)
#  client_target_delivery_schedule :string(255)
#  owner_of_the_etask              :string(255)
#  status_of_the_enquiry           :string(255)
#  tenant_id                       :string(255)
#  client_id                       :string(255)
#  created_at                      :datetime         not null
#  updated_at                      :datetime         not null
#

class Enquiry < ApplicationRecord
end

app/controllers/admin/enquiries_controller.rb
module Admin
  class EnquiriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Enquiry.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Enquiry.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_enquiry, only: [:show, :update, :destroy]

  # GET /enquiries
  # GET /enquiries.json
  def index
    @enquiries = Enquiry.all
  end

  # GET /enquiries/1
  # GET /enquiries/1.json
  def show
  end
   # GET /enquiries/new
  def new

    @enquiry = Enquiry.new
  
  end
  # POST /enquiries
  # POST /enquiries.json
  def create
    @enquiry = Enquiry.new(enquiry_params)

    if @enquiry.save
      render :show, status: :created, location: @enquiry
    else
      render json: @enquiry.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /enquiries/1
  # PATCH/PUT /enquiries/1.json
  def update
    if @enquiry.update(enquiry_params)
      render :show, status: :ok, location: @enquiry
    else
      render json: @enquiry.errors, status: :unprocessable_entity
    end
  end

  # DELETE /enquiries/1
  # DELETE /enquiries/1.json
  def destroy
    @enquiry.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry
      @enquiry = Enquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enquiry_params
      params.require(:enquiry).permit(:client_name, :enquiry_for, :color, :material, :gsm, :quantity, :sizes, :printing, :embroidery, :place_of_printing, :payment_terms, :client_target_price, :client_target_delivery_schedule, :owner_of_the_etask, :status_of_the_enquiry, :tenant_id, :client_id)
    end
end

app/views/enquiries/_form.html.erb
<%= form_with(model: enquiry, local: true) do |form| %>
  <% if enquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enquiry.errors.count, "error") %> prohibited this enquiry from being saved:</h2>

      <ul>
      <% enquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_name %>
    <%= form.text_field :client_name %>
  </div>

  <div class="field">
   <%= form.label :enquiry_for %>
    <input type="checkbox" id= "enquiry_for"name="item" value="Polo"  />Polo 
    <input name="item" type="hidden" value ="0" />
    <input type="checkbox" name="item" value="Round neck"> Round neck
     <input type="checkbox" name="item" value="Cap"> Cap 
   
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>  

  <div class="field">
    <%= form.label :material %>
    <%= form.text_field :material %>
  </div>

  <div class="field">
    <%= form.label :gsm %>
    <%= form.text_field :gsm %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :sizes %>
    <%= form.text_field :sizes %>
  </div>

  <div class="field">
    <%= form.label :printing %>
     <input type="checkbox" name="item" value="Screen print"> Screen print
      <input type="checkbox" name="item" value="Sublimation"> Sublimation
  </div>

  <div class="field">
    <%= form.label :embroidery %>
    <%= form.text_field :embroidery %>
  </div>

  <div class="field">
    <%= form.label :place_of_printing %>
     <input type="checkbox" name="item" value="Left chest"> Left chest
     <input type="checkbox" name="item" value="Right chest"> Right chest
     <input type="checkbox" name="item" value="Front"> Front
     <input type="checkbox" name="item" value="Rear"> Rear
     <input type="checkbox" name="item" value="Right sleeve"> Right sleeve 
     <input type="checkbox" name="item" value="Left sleeve"> Left sleeve
     <input type="checkbox" name="item" value="Moon yoke"> Moon yoke
     <input type="checkbox" name="item" value="Sides"> Sides
     <input type="checkbox" name="item" value="Others"> Others
   </div>  

  <div class="field">
    <%= form.label :payment_terms %>
    <%= form.text_field :payment_terms %>
  </div>

  <div class="field">
    <%= form.label :client_target_price %>
    <%= form.text_field :client_target_price %>
  </div>

  <div class="field">
    <%= form.label :client_target_delivery_schedule %>
    <%= form.text_field :client_target_delivery_schedule %>
  </div>

  <div class="field">
    <%= form.label :offered_price %>
    <%= form.text_field :offered_price %>
  </div>

  <div class="field">
    <%= form.label :offered_delivery_schedule %>
    <%= form.text_field :offered_delivery_schedule %>
  </div>

  <div class="field">
    <%= form.label :owner_of_the_etask %>
    <%= form.text_field :owner_of_the_etask %>
  </div>

  <div class="field">
    <%= form.label :status_of_the_enquiry %>
    <%= form.text_field :status_of_the_enquiry %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enquiries/edit.html.erb
<h1>Editing Enquiry</h1>

<%= render 'form', enquiry: @enquiry %>

<%= link_to 'Show', @enquiry %> |
<%= link_to 'Back', enquiries_path %>

app/views/enquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enquiries</h1>

<table>
  <thead>
    <tr>
      <th>Client name</th>
      <th>Enquiry for</th>
     
      <th>Color</th>
      <th>Material</th>
      <th>Gsm</th>
      <th>Quantity</th>
      <th>Sizes</th>
      <th>Printing</th>
      <th>Embroidery</th>
      <th>Place of printing</th>
      <th>Payment terms</th>
      <th>Client target price</th>
      <th>Client target delivery schedule</th>
      <th>Offered price</th>
      <th>Offered delivery schedule</th>
      <th>Owner of the etask</th>
      <th>Status of the enquiry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enquiries.each do |enquiry| %>
      <tr>
        <td><%= enquiry.client_name %></td>
        <td><%= enquiry.enquiry_for %></td>

        <td><%= enquiry.color %></td>
        <td><%= enquiry.material %></td>
        <td><%= enquiry.gsm %></td>
        <td><%= enquiry.quantity %></td>
        <td><%= enquiry.sizes %></td>
        <td><%= enquiry.printing %></td>
        <td><%= enquiry.embroidery %></td>
        <td><%= enquiry.place_of_printing %></td>
        <td><%= enquiry.payment_terms %></td>
        <td><%= enquiry.client_target_price %></td>
        <td><%= enquiry.client_target_delivery_schedule %></td>
        <td><%= enquiry.offered_price %></td>
        <td><%= enquiry.offered_delivery_schedule %></td>
        <td><%= enquiry.owner_of_the_etask %></td>
        <td><%= enquiry.status_of_the_enquiry %></td>
        <td><%= link_to 'Show', enquiry if policy(enquiry).show? %></td>
        <td><%= link_to 'Edit', edit_enquiry_path(enquiry) if policy(enquiry).update?  %></td>
        <td><%= link_to 'Destroy', enquiry, method: :delete, data: { confirm: 'Are you sure?' } if policy(enquiry).destroy? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enquiry', new_enquiry_path %>

app/views/enquiries/new.html.erb
<h1>New Enquiry</h1>

<%= render 'form', enquiry: @enquiry %>

<%= link_to 'Back', enquiries_path %>

app/views/enquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client name:</strong>
  <%= @enquiry.client_name %>
</p>

<p>
  <strong>Enquiry for:</strong>
  <%= @enquiry.enquiry_for %>
</p>

<p>
  <strong>Color:</strong>
  <%= @enquiry.color %>
</p>

<p>
  <strong>Material:</strong>
  <%= @enquiry.material %>
</p>

<p>
  <strong>Gsm:</strong>
  <%= @enquiry.gsm %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @enquiry.quantity %>
</p>

<p>
  <strong>Sizes:</strong>
  <%= @enquiry.sizes %>
</p>

<p>
  <strong>Printing:</strong>
  <%= @enquiry.printing %>
</p>

<p>
  <strong>Embroidery:</strong>
  <%= @enquiry.embroidery %>
</p>

<p>
  <strong>Place of printing:</strong>
  <%= @enquiry.place_of_printing %>
</p>

<p>
  <strong>Payment terms:</strong>
  <%= @enquiry.payment_terms %>
</p>

<p>
  <strong>Client target price:</strong>
  <%= @enquiry.client_target_price %>
</p>

<p>
  <strong>Client target delivery schedule:</strong>
  <%= @enquiry.client_target_delivery_schedule %>
</p>

<p>
  <strong>Offered price:</strong>
  <%= @enquiry.offered_price %>
</p>

<p>
  <strong>Offered delivery schedule:</strong>
  <%= @enquiry.offered_delivery_schedule %>
</p>

<p>
  <strong>Owner of the etask:</strong>
  <%= @enquiry.owner_of_the_etask %>
</p>

<p>
  <strong>Status of the enquiry:</strong>
  <%= @enquiry.status_of_the_enquiry %>
</p>

<%= link_to 'Edit', edit_enquiry_path(@enquiry)  if policy(@enquiry).edit? %>

<% if policy(@enquiry).destroy? %>
    <%= link_to "Delete", @enquiry, method: :delete, class: 'btn btn-danger' %>
<% end %>
<%= link_to 'Back', enquiries_path %>